# Generated by Django 3.2.3 on 2021-05-18 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=60)),
                ('frequency', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Urlword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.TextField()),
                ('words', models.ManyToManyField(to='Base.Word')),
            ],
        ),
    ]
